### ISSUE TITLE
isValid method returns false, when parse returns isValid true

### ISSUE THREAD

**Issue by Lalitha-Iyer** [thom4parisot/tld.js#112]
url : https://google.com

**Comment by remusao** [comment]
Hello @Lalitha-Iyer 

Thanks for reporting. I think the API might be confusing here. The `isValid` method actually checks if the input is a valid *domain* (e.g.: `google.com` would be a valid domain, but `http://google.com` would not since it has the protocol). But then the `parse` functions returns `isValid` if the input *contains* a valid domain, after URL parsing. Seems like we use the same name for two different things.

We could probably rename things a bit. What about renaming the `isValid` method to `isHostname`, and leave the `isValid` in `parse`'s result unchanged?

**Comment by remusao** [comment]
Actually I just noticed that the documentation in the README is also wrong regarding `isValid`. So I can propose the following solution (but feel free to suggest something else as well, all feedback is more than welcome!):

Have a `isHostname` or `isValidHostname` in the API, that just checks if the input is already a valid hostname. We could leave the `isValid` and changes it's behavior to be in line with the documentation and the behavior of `parse`.

It seems that we introduced a breaking change with `isValid` at some point and did not reflect it in the documentation.

FYI @oncletom
