### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by ElectronicsArchiver** [thom4parisot/tld.js#146]
@thom4parisot Have you completely abandoned this project?

If so, could you at least let someone else maintain this?

*No commits in 5 years holding up `161,689` weekly downloads..*

**Comment by remusao** [comment]
For what it's worth I've been maintaining a fork of `tld.js` here: https://github.com/remusao/tldts/

If there are some urgent fixes we might be able to get them in `tld.js`, though. Happy to help since I'm pretty familiar with the code-base (we'd still need to check if we can merge and publish new versions).

**Comment by ElectronicsArchiver** [comment]
@remusao Btw, are you on Matrix?

**Comment by remusao** [comment]
No.

**Comment by ElectronicsArchiver** [comment]
@remusao Oh, what a shame, I would have loved to talk to you ( somewhat unrelated to this )

**Comment by alanhamlett** [comment]
Be careful when people ask to maintain your open source project. It's a common attack vector:

https://news.ycombinator.com/item?id=39865810

**Comment by thom4parisot** [comment]
Hello and sorry for not having responded to any message since a couple of years.

Some projects are shifting for me this summer: I'd be happy to work a solid new version of this package, or to offer a migration path towards an already better/more modern package.

**Comment by alanhamlett** [comment]
I'm using https://github.com/remusao/tldts that looks to be well maintained.
